### ISSUE TITLE
different approach for rolling on a table

### ISSUE THREAD

**Issue by majestic-owl448** [ieahleen/randomTreasure#5]
./utils:
total 12

- [x] -rw-r--r-- 1 gitpod gitpod 4458 Jun 19 14:37 helpers.js
- - [x] two randomItemFromTable arrays(?) 
- [x] -rw-r--r-- 1 gitpod gitpod  179 Jun 14 20:08 numberOfCoins.js

./individualTreasureTables:
total 16

- [x] -rw-r--r-- 1 gitpod gitpod 512 Jun 14 12:44 challenge0-4.js
- [x] -rw-r--r-- 1 gitpod gitpod 671 Jun 14 12:44 challenge5-10.js
- [x] -rw-r--r-- 1 gitpod gitpod 614 Jun 14 12:44 challenge11-16.js
- [x] -rw-r--r-- 1 gitpod gitpod 529 Jun 14 20:08 challenge17+.js

./lists:
total 24

- [x] -rw-r--r-- 1 gitpod gitpod   286 Jun 11 10:48 other.js
- [x] -rw-r--r-- 1 gitpod gitpod 13651 Jun 11 10:48 spells.js
- [x] -rw-r--r-- 1 gitpod gitpod   480 Jun 11 10:48 weapons.js

./tables:
total 60

- [x] -rw-r--r-- 1 gitpod gitpod 2724 Jun 14 12:44 artObjects.js
- [x] -rw-r--r-- 1 gitpod gitpod 4547 Jun 14 20:08 gems.js
- [x] -rw-r--r-- 1 gitpod gitpod  702 Jun 14 20:08 magicItemsA.js
- [x] -rw-r--r-- 1 gitpod gitpod 2705 Jun 19 14:47 magicItemsB.js
- [x] -rw-r--r-- 1 gitpod gitpod 1873 Jun 14 20:08 magicItemsC.js
- [x] -rw-r--r-- 1 gitpod gitpod 1172 Jun 14 20:08 magicItemsD.js
- [x] -rw-r--r-- 1 gitpod gitpod  630 Jun 14 20:08 magicItemsE.js
- [x] -rw-r--r-- 1 gitpod gitpod 3277 Jun 14 20:08 magicItemsF.js
- [x] -rw-r--r-- 1 gitpod gitpod 6212 Jun 19 14:42 magicItemsG.js
- [x] -rw-r--r-- 1 gitpod gitpod 4926 Jun 19 14:46 magicItemsH.js
- [x] -rw-r--r-- 1 gitpod gitpod 4607 Jun 14 20:08 magicItemsI.js

./treasureHoardTables:
total 16

- [x] -rw-r--r-- 1 gitpod gitpod 1845 Jun 19 14:39 challenge0-4.js
- [x] -rw-r--r-- 1 gitpod gitpod 2738 Jun 14 20:08 challenge5-10.js
- [x] -rw-r--r-- 1 gitpod gitpod 2665 Jun 19 14:30 challenge11-16.js
- [x] -rw-r--r-- 1 gitpod gitpod 2495 Jun 14 20:08 challenge17+.js

---
 
Thanks @alpox

I had an idea for the lots of <= calls:
```
const randomItemFromTable = (maxDie, dist) => (...args) => {
  const num = rwn(maxDie);
  const keys = Object.keys(dist).map((d) => parseInt(d)).sort((a, b) => a - b);
  const key = keys.find((key) => num <= key);
  const result = dist[key];
  return typeof result === "function"
    ? result(...args)
    : result;
}
```

This helper function would allow you to define things neatly. E.g:
```
const carpetSizeDefinition = [
  100,
  {
    20: "3 ft. x 5 ft.",
    55: "4 ft. x 6 ft.",
    80: "5 ft. x 7 ft.",
    100: "6 ft. x 9 ft."
  }
]

const carpetSize = randomItemFromTable(...carpetSizeDefinition);
```

```
console.log(carpetSize())
const randomPatchDefinition = [
  100,
  {
    8: "Bag of 100 gp",
    15: "Silver coffer",
    22: "Iron door",
    30: () => [
      gems100(),
      gems100(),
      gems100(),
      gems100(),
      gems100(),
      gems100(),
      gems100(),
      gems100(),
      gems100(),
      gems100(),
    ],
    83: randomItemFromTable(6, {
        3: () => `${ranArr(spells1)} spell scroll (1st level)`,
        5: () => `${ranArr(spells2)} spell scroll (2nd level)`,
        6: () => `${ranArr(spells3)} spell scroll (3rd level)`,
      }),
    100: "Portable ram",
  },
];
```

for more involved cases

**Comment by majestic-owl448** [comment]
I extended a bit the possibilities for those challenges

And changed a bit the helpers

```
function rwn(max) {
  return Math.floor(Math.random() * max) + 1;
}

```
```
const randomItemFromTable =
  (dist) =>
  (num, ...args) => {
    const keys = Object.keys(dist)
      .map((d) => parseInt(d))
      .sort((a, b) => a - b);
    const key = keys.find((key) => num <= key);
    const result = dist[key];
    return typeof result === "function" ? result(...args) : result;
  };

const partition = (arr, num) => {
  const result = [];
  for (let i = 0; i < arr.length; i += num) {
    result.push(arr.slice(i, i + num));
  }
  return result;
};

const randomRangeSelection =
  (ranges) =>
  (num, ...args) => {
    const parts = partition(ranges, 2);
    const [rangeDef, rangeResult] = parts.find(([rangeDef, result]) => {
      if (!result) return true;
      return rangeDef.some(([from, to]) => num >= from && num <= to);
    });
    const result = rangeResult ? rangeResult : rangeDef;
    return typeof result === "function" ? result(...args) : result;
  };
```

Given these helpers

You can do challenge 11-16 like:
```
const randomGem = randomRangeSelection([
  [
    [10, 12],
    [13, 15],
    [17, 40],
  ],
  () => ({ "500 gp gems": "test" }),
  [
    [13, 15],
    [27, 29],
  ],
  () => ({ "1000 gp gems": "test2" }),
  [[50, 52]],
  () => ({ "250 gp gems": "test3" }),
  () => ({ "750 gp gems": "test4" }), // else / default case
]);

const randomItem = randomItemFromTable({
  15: (v) => v,
  29: (v) => ({ ...v, "Magic Items": ["foobar"] }),
  50: (v) => ({ ...v, "Magic Items": ["fa"] }),
  100: (v) => ({ ...v, "Magic Items": ["fa"] }),
});

function treasureG() {
  const die = rwn(100);
  const treasure = randomGem(die);
  return randomItem(die, treasure);
}

console.log(treasureG());
```

**Comment by ieahleen** [comment]
./individualTreasureTables:
total 16

- [ ] -rw-r--r-- 1 gitpod gitpod 512 Jun 14 12:44 challenge0-4.js
- [ ] -rw-r--r-- 1 gitpod gitpod 614 Jun 14 12:44 challenge11-16.js
- [ ] -rw-r--r-- 1 gitpod gitpod 529 Jun 14 20:08 challenge17+.js
- [ ] -rw-r--r-- 1 gitpod gitpod 671 Jun 14 12:44 challenge5-10.js

./lists:
total 24

- [ ] -rw-r--r-- 1 gitpod gitpod   286 Jun 11 10:48 other.js
- [ ] -rw-r--r-- 1 gitpod gitpod 13651 Jun 11 10:48 spells.js
- [ ] -rw-r--r-- 1 gitpod gitpod   480 Jun 11 10:48 weapons.js

./tables:
total 60

- [ ] -rw-r--r-- 1 gitpod gitpod 2724 Jun 14 12:44 artObjects.js
- [ ] -rw-r--r-- 1 gitpod gitpod 4547 Jun 14 20:08 gems.js
- [ ] -rw-r--r-- 1 gitpod gitpod  702 Jun 14 20:08 magicItemsA.js
- [ ] -rw-r--r-- 1 gitpod gitpod 2705 Jun 19 14:47 magicItemsB.js
- [ ] -rw-r--r-- 1 gitpod gitpod 1873 Jun 14 20:08 magicItemsC.js
- [ ] -rw-r--r-- 1 gitpod gitpod 1172 Jun 14 20:08 magicItemsD.js
- [ ] -rw-r--r-- 1 gitpod gitpod  630 Jun 14 20:08 magicItemsE.js
- [ ] -rw-r--r-- 1 gitpod gitpod 3277 Jun 14 20:08 magicItemsF.js
- [ ] -rw-r--r-- 1 gitpod gitpod 6212 Jun 19 14:42 magicItemsG.js
- [ ] -rw-r--r-- 1 gitpod gitpod 4926 Jun 19 14:46 magicItemsH.js
- [ ] -rw-r--r-- 1 gitpod gitpod 4607 Jun 14 20:08 magicItemsI.js

./treasureHoardTables:
total 16

- [ ] -rw-r--r-- 1 gitpod gitpod 1845 Jun 19 14:39 challenge0-4.js
- [ ] -rw-r--r-- 1 gitpod gitpod 2665 Jun 19 14:30 challenge11-16.js
- [ ] -rw-r--r-- 1 gitpod gitpod 2495 Jun 14 20:08 challenge17+.js
- [ ] -rw-r--r-- 1 gitpod gitpod 2738 Jun 14 20:08 challenge5-10.js

./utils:
total 12

- [ ] -rw-r--r-- 1 gitpod gitpod 4458 Jun 19 14:37 helpers.js
- [ ] -rw-r--r-- 1 gitpod gitpod  179 Jun 14 20:08 numberOfCoins.js
